export const SUBSCRIBE_FOLDER_PREFERENCE = 'SUBSCRIBE_FOLDER_PREFERENCE';
export const UNSUBSCRIBE_FOLDER_PREFERENCE = 'UNSUBSCRIBE_FOLDER_PREFERENCE';
export const FETCH_FOLDER_PREFERENCE = 'FETCH_FOLDER_PREFERENCES';
export const RECEIVE_FOLDER_PREFERENCE = 'RECEIVE_FOLDER_PREFERENCES';

export const TOGGLE_FOLDER_COLLAPSE = 'TOGGLE_BOOKMARK_FOLDER_COLLAPSE';
