export const SUBSCRIBE_FOLDER_PREFERENCES = 'SUBSCRIBE_FOLDER_PREFERENCES';
export const UNSUBSCRIBE_FOLDER_PREFERENCES = 'UNSUBSCRIBE_FOLDER_PREFERENCES';

export const RECEIVE_FOLDER_PREFERENCES = 'RECEIVE_FOLDER_PREFERENCES';

export const TOGGLE_FOLDER = 'TOGGLE_FOLDER';
