export const SUBSCRIBE_FOLDER_ITEM_PREFERENCES = 'SUBSCRIBE_FOLDER_ITEM_PREFERENCES';
export const UNSUBSCRIBE_FOLDER_ITEM_PREFERENCES = 'UNSUBSCRIBE_FOLDER_ITEM_PREFERENCES';

export const RECEIVE_FOLDER_ITEM_PREFERENCES = 'RECEIVE_FOLDER_ITEM_PREFERENCES';
