export const RECEIVE_VISIBILITIES = 'RECEIVE_VISIBILITIES';
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';

export const RECEIVE_SELECTED_THEME = 'RECEIVE_SELECTED_THEME';
export const SELECT_THEME = 'SELECT_THEME';
export const RENDER_THEME = 'RENDER_THEME';
