export const RECEIVE_THEMES = 'RECEIVE_THEMES';
export const SELECT_THEME = 'SELECT_THEME';
export const RENDER_THEME = 'RENDER_THEME';

export const SET_APP_PREFERENCE = 'SET_APP_PREFERENCE';
export const RECEIVE_APP_PREFERENCE = 'RECEIVE_APP_PREFERENCE';
