export const SET_APP_PREFERENCE = 'SET_APP_PREFERENCE';
export const RECEIVE_APP_PREFERENCE = 'RECEIVE_APP_PREFERENCE';

export const RECEIVE_PURCHASES = 'RECEIVE_PURCHASES';
export const MAKE_DONATION = 'MAKE_DONATION';
