export const SUBSCRIBE_CHROME_APPS = 'SUBSCRIBE_CHROME_APPS';
export const UNSUBSCRIBE_CHROME_APPS = 'UNSUBSCRIBE_CHROME_APPS';
export const FETCH_CHROME_APPS = 'FETCH_CHROME_APPS';
export const RECEIVE_CHROME_APPS = 'RECEIVE_CHROME_APPS';
