export const SUBSCRIBE_SELECTED_THEME = 'SUBSCRIBE_SELECTED_THEME';
export const UNSUBSCRIBE_SELECTED_THEME = 'UNSUBSCRIBE_SELECTED_THEME';
export const FETCH_SELECTED_THEME = 'FETCH_SELECTED_THEME';
export const RECEIVE_SELECTED_THEME = 'RECEIVE_SELECTED_THEME';
