export const SUBSCRIBE_SELECTED_THEME = 'SUBSCRIBE_SELECTED_THEME';
export const UNSUBSCRIBE_SELECTED_THEME = 'UNSUBSCRIBE_SELECTED_THEME';
export const RECEIVE_SELECTED_THEME = 'RECEIVE_SELECTED_THEME';
export const SELECT_THEME = 'SELECT_THEME';
export const RENDER_THEME = 'RENDER_THEME';
