export const OPEN_FOLDER_ITEM_EDITOR = 'OPEN_FOLDER_ITEM_EDITOR';
export const CHANGE_FOLDER_ITEM_EDITOR = 'CHANGE_FOLDER_ITEM_EDITOR';
export const CANCEL_FOLDER_ITEM_EDITOR = 'CANCEL_FOLDER_ITEM_EDITOR';

export const SAVE_FOLDER_ITEM_EDITOR = 'SAVE_FOLDER_ITEM_EDITOR';
export const SAVE_SUCCEEDED_FOLDER_ITEM_EDITOR = 'SAVE_SUCCEEDED_FOLDER_ITEM_EDITOR';
export const SAVE_FAILED_FOLDER_ITEM_EDITOR = 'SAVE_FAILED_FOLDER_ITEM_EDITOR';

export const REMOVE_FOLDER_ITEM_EDITOR = 'REMOVE_FOLDER_ITEM_EDITOR';
export const REMOVE_SUCCEEDED_FOLDER_ITEM_EDITOR = 'REMOVE_SUCCEEDED_FOLDER_ITEM_EDITOR';
export const REMOVE_FAILED_FOLDER_ITEM_EDITOR = 'REMOVE_FAILED_FOLDER_ITEM_EDITOR';
