export const SUBSCRIBE_VISIBILITIES = 'SUBSCRIBE_VISIBILITIES';
export const UNSUBSCRIBE_VISIBILITIES = 'UNSUBSCRIBE_VISIBILITIES';
export const FETCH_VISIBILITIES = 'FETCH_VISIBILITIES';
export const RECEIVE_VISIBILITIES = 'RECEIVE_VISIBILITIES';
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
