export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const RECEIVE_BOOKMARKS = 'RECEIVE_BOOKMARKS';

export const FETCH_CHROME_APPS = 'FETCH_CHROME_APPS';
export const RECEIVE_CHROME_APPS = 'RECEIVE_CHROME_APPS';

export const FETCH_TOP_SITES = 'FETCH_TOP_SITES';
export const RECEIVE_TOP_SITES = 'RECEIVE_TOP_SITES';

export const RECEIVE_FOLDER_PREFERENCES = 'RECEIVE_FOLDER_PREFERENCES';
export const TOGGLE_FOLDER = 'TOGGLE_FOLDER';

export const RECEIVE_FOLDER_ITEM_PREFERENCES = 'RECEIVE_FOLDER_ITEM_PREFERENCES';
export const SAVE_FOLDER_ITEM_PREFERENCE = 'SAVE_FOLDER_ITEM_PREFERENCE';
