export const SUBSCRIBE_BOOKMARK_PREFERENCE = 'SUBSCRIBE_BOOKMARK_PREFERENCE';
export const UNSUBSCRIBE_BOOKMARK_PREFERENCE = 'UNSUBSCRIBE_BOOKMARK_PREFERENCE';
export const RECEIVE_BOOKMARK_PREFERENCE = 'RECEIVE_BOOKMARK_PREFERENCES';
