export const SUBSCRIBE_BOOKMARKS = 'SUBSCRIBE_BOOKMARKS';
export const UNSUBSCRIBE_BOOKMARKS = 'UNSUBSCRIBE_BOOKMARKS';
export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const RECEIVE_BOOKMARKS = 'RECEIVE_BOOKMARKS';
export const UPDATING_BOOKMARK = 'UPDATING_BOOKMARK';
export const UPDATED_BOOKMARK = 'UPDATED_BOOKMARK';
export const REMOVING_BOOKMARK = 'REMOVING_BOOKMARK';
export const REMOVED_BOOKMARK = 'REMOVED_BOOKMARK';

export const SUBSCRIBE_CHROME_APPS = 'SUBSCRIBE_CHROME_APPS';
export const UNSUBSCRIBE_CHROME_APPS = 'UNSUBSCRIBE_CHROME_APPS';
export const FETCH_CHROME_APPS = 'FETCH_CHROME_APPS';
export const RECEIVE_CHROME_APPS = 'RECEIVE_CHROME_APPS';

export const OPEN_BOOKMARK_EDIT = 'OPEN_BOOKMARK_EDIT';
export const CHANGE_BOOKMARK_EDIT = 'CHANGE_BOOKMARK_EDIT';
export const CANCEL_BOOKMARK_EDIT = 'CANCEL_BOOKMARK_EDIT';
