export const SUBSCRIBE_BOOKMARKS = 'SUBSCRIBE_BOOKMARKS';
export const UNSUBSCRIBE_BOOKMARKS = 'UNSUBSCRIBE_BOOKMARKS';

export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const RECEIVE_BOOKMARKS = 'RECEIVE_BOOKMARKS';
