name: cypress

on:
  pull_request:
    paths:
      - .github/workflows/cypress.yaml
      - src/**
      - cypress/**
      - package.json
      - yarn.lock
  push:
    branches:
      - main
    paths:
      - .github/workflows/cypress.yaml
      - src/**
      - cypress/**
      - package.json
      - yarn.lock

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v4
        with:
          component: true
      - uses: int128/upload-artifact-wiki-action@v1
        id: upload-artifact-wiki
        with:
          path: cypress/screenshots/**/*.png
      - uses: int128/comment-action@v1
        with:
          post: |
            <img src="${{ steps.upload-artifact-wiki.outputs.url }}/cypress/screenshots/App.cy.tsx/App%20--%20mounts.png">
