name: cypress

on:
  pull_request:
    paths:
      - .github/workflows/cypress.yaml
      - src/**
      - cypress/**
      - cypress.*
      - '*.json'
      - pnpm-lock.yaml
  push:
    branches:
      - main
    paths:
      - .github/workflows/cypress.yaml
      - src/**
      - cypress/**
      - cypress.*
      - '*.json'
      - pnpm-lock.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: cypress-io/github-action@v4
        with:
          component: true
          browser: chrome
      - uses: int128/upload-artifact-wiki-action@v1
        id: upload-artifact-wiki
        with:
          path: cypress/screenshots/**/*.png
      - uses: int128/comment-action@v1
        with:
          post: |
            <table>
              <tr>
                <td><img src="${{ steps.upload-artifact-wiki.outputs.url }}/cypress/screenshots/App.cy.tsx/App%20--%20mounts.png"></td>
                <td><img src="${{ steps.upload-artifact-wiki.outputs.url }}/cypress/screenshots/App.cy.tsx/App%20--%20enables%20dark%20mode.png"></td>
              </tr>
              <tr>
                <td><img src="${{ steps.upload-artifact-wiki.outputs.url }}/cypress/screenshots/App.cy.tsx/App%20--%20opens%20the%20bookmark%20editor.png"></td>
                <td></td>
              </tr>
            </table>
