name: release

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/release.yaml
      - manifest.json
      - package.json
      - pnpm-lock.yaml
  push:
    branches:
      - main
    paths:
      - .github/workflows/release.yaml
      - manifest.json
      - package.json
      - pnpm-lock.yaml
    tags:
      - '*'

jobs:
  zip:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm run build
      - run: sed -i -e "s|0.0.0.0|$GITHUB_REF_NAME|" dist/manifest.json
      - run: cd dist && zip -r ../dist.zip .
      - run: zipinfo dist.zip
      - if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist.zip
          path: dist.zip
      - if: github.ref_type == 'tag'
        run: gh release upload "${{ github.ref_name }}" dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
